# Generated by Django 4.1.4 on 2023-03-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact_delete_opt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='image',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='info',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
